version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Halifax
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: jest
    versions:
    - "*"
  - dependency-name: jest-cli
    versions:
    - "*"
  - dependency-name: puppeteer
    versions:
    - "*"
  - dependency-name: "@types/jest"
    versions:
    - "*"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: bl
    versions:
    - 4.0.4
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
