/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Service,
} from 'types/Service';


export namespace Components {

  interface ManifoldMarketplace {
    'theme'?: 'light' | 'dark';
  }
  interface ManifoldMarketplaceAttributes extends StencilHTMLAttributes {
    'theme'?: 'light' | 'dark';
  }

  interface StencilServiceCard {
    'description': string;
    'logo': string;
    'name': string;
    'tags': string;
  }
  interface StencilServiceCardAttributes extends StencilHTMLAttributes {
    'description'?: string;
    'logo'?: string;
    'name'?: string;
    'tags'?: string;
  }

  interface ServiceGrid {
    'services': Service[];
    'themeColor': { [index: string]: string };
  }
  interface ServiceGridAttributes extends StencilHTMLAttributes {
    'services'?: Service[];
    'themeColor'?: { [index: string]: string };
  }
}

declare global {
  interface StencilElementInterfaces {
    'ManifoldMarketplace': Components.ManifoldMarketplace;
    'StencilServiceCard': Components.StencilServiceCard;
    'ServiceGrid': Components.ServiceGrid;
  }

  interface StencilIntrinsicElements {
    'manifold-marketplace': Components.ManifoldMarketplaceAttributes;
    'stencil-service-card': Components.StencilServiceCardAttributes;
    'service-grid': Components.ServiceGridAttributes;
  }


  interface HTMLManifoldMarketplaceElement extends Components.ManifoldMarketplace, HTMLStencilElement {}
  var HTMLManifoldMarketplaceElement: {
    prototype: HTMLManifoldMarketplaceElement;
    new (): HTMLManifoldMarketplaceElement;
  };

  interface HTMLStencilServiceCardElement extends Components.StencilServiceCard, HTMLStencilElement {}
  var HTMLStencilServiceCardElement: {
    prototype: HTMLStencilServiceCardElement;
    new (): HTMLStencilServiceCardElement;
  };

  interface HTMLServiceGridElement extends Components.ServiceGrid, HTMLStencilElement {}
  var HTMLServiceGridElement: {
    prototype: HTMLServiceGridElement;
    new (): HTMLServiceGridElement;
  };

  interface HTMLElementTagNameMap {
    'manifold-marketplace': HTMLManifoldMarketplaceElement
    'stencil-service-card': HTMLStencilServiceCardElement
    'service-grid': HTMLServiceGridElement
  }

  interface ElementTagNameMap {
    'manifold-marketplace': HTMLManifoldMarketplaceElement;
    'stencil-service-card': HTMLStencilServiceCardElement;
    'service-grid': HTMLServiceGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
