name: e2e

on:
  deployment_status:
    branches:
      - sslotsky/test-cafe-action

jobs:
  test:
    env:
      DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
    if:
      github.event.deployment_status.state == 'SUCCESS' &&
      github.event.deployment_status.creator.login == 'now[bot]'
    name: Run e2e tests with TestCafe
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Pull the Docker image
        run: docker pull testcafe/testcafe
      - name: Tests to Run
        run: ls /home/runner/work/ui/ui/e2e
      - name: Run TestCafe
        run:
          docker run -e DEPLOY_URL -v /home/runner/work/ui/ui/e2e:/tests -i testcafe/testcafe
          chromium /tests/
